### ISSUE TITLE
Image size limit

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#107]
Either limit image size or automatically resize/downsample images to smaller size when uploading.

**Comment by mdaxtman** [comment]
which of those two would you recommend for this? What would be the size limit that would either trigger a compression or disallow an upload?

**Comment by rgerstenberger** [comment]
I think resampling is ideal but much more work. I'm not sure what a good size limit would be. It would depend on plot.ly's upload API size limit and the expected number of images and size of presentation without images.

**Comment by mdaxtman** [comment]
alright, I'll confer with them, I see that some of the other issues filed here have been related to size limits with their API.
