### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#111]
Cross platform menu bar with keyboard events

*Spectacle Editor:*
  -Quit

*File:*
  -Save
  -Save as (maybe?)
  -Open
  -Export to PDF

*Edit:*
  -Undo
  -Redo
  -delete element (if one is selected)

*View*
  -Slideshow

@paulathevalley, @kenwheeler, @mdaxtman @coopy  Anything I missed?

**Comment by coopy** [comment]
Should it include the depth controls (move one step/to back, move one step/to front)?

**Comment by rgerstenberger** [comment]
Yes I think that's a reasonable include.

**Comment by mdtusz** [comment]
For _File_, it would also be good to include _New_. I frequently find myself closing the editor window and having to restart the application to get a blank/new presentation.

**Comment by rgerstenberger** [comment]
@mdtusz #161 should cover that :) . This was meant to cover cross platform menu basics which are completed. Any other menu bugs/features should be opened in separate issues.
