### ISSUE TITLE
Prompt user to save work if closing with unsaved changes

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#149]
Notify the user if they are closing the app with unsaved or unpublished changes. Allow them to save or publish from the prompt.

**Comment by mdaxtman** [comment]
@rgerstenberger publish from the prompt? I'm not sure what you mean. Does that mean upload the presentation?

**Comment by rgerstenberger** [comment]
Yes, upload to plot.ly === publish. I'm imagining some users won't ever use `file -> save` and instead will use `upload to plot.ly` as their saving mechanism. In that case, it could be confusing to show a save file dialog and keep saved state in multiple places. Maybe not, @bmathews @paulathevalley thoughts?

**Comment by mdaxtman** [comment]
@bmathews and @paulathevalley and if we decide to implement this, what verbage would we use? "publish"? "upload"?

**Comment by paulathevalley** [comment]
Without talking to users or having data, I can’t say for certain how they will use the app. 

I would imagine `File > Save` or pressing `cmd + s` is so common between apps, that it’ll happen almost unconsciously: do you remember the last time you actively saved a file in your text editor? 

I suspect Upload/Publish to plot.ly be may associated with "sharing this presentation with my colleagues" which may only happen once the presentation is completed. Again, I really have no idea for sure. 

If changes are made to a presentation, then I think it definitely makes sense to show _some_ dialog that’s warning about unsaved changes. Could there be more than one option: "Save Changes", "Upload to Plot.ly", and "Discard" in this dialog??

**Comment by mdaxtman** [comment]
I have a working draft at present. The options are "Save", "Don't Save", and "Cancel". I can add a 4th option in there. "Don't Save" would have to become "Discard". Would a 4th option become cluttered?

**Comment by paulathevalley** [comment]
Hmmm, four does seem like a lot. Some applications will automatically save the file on close, but the question here is whether to save it locally or upload it to plot.ly, right? 

Would it _ever_ be possible for someone to upload a file to plot.ly without saving it locally? 

Assuming the answer is no, my suggestion is to keep it simple. Don't introduce "Upload to plot.ly" in the dialog. Only keep it about saving it locally. 

On close, if the file has already been saved, I would suggest display no prompt and automatically save it.

On close, if the file isn’t saved:

Do you want to save this new presentation?
[Save]
[Cancel]
[Delete]
