### ISSUE TITLE
Add Toggle Developer Tools to View menu?

### ISSUE THREAD

**Issue by jackparmer** [FormidableLabs/spectacle-editor#164]
It can be hard to help users debug and report potential issues without easy access to Dev Tools. 

_nteract_ includes "Toggle Developer Tools" under their view menu. Does this make sense for SpecEd?

![image](https://cloud.githubusercontent.com/assets/1865834/18056623/a17eb496-6dda-11e6-8faf-0cb12bb2e808.png)

**Comment by mdaxtman** [comment]
@rgerstenberger what are your thoughts on this idea?

**Comment by rgerstenberger** [comment]
This seems reasonable given the fact that it's an open source project.
