### ISSUE TITLE
Potential unicode issue in SpecEd viewer

### ISSUE THREAD

**Issue by jackparmer** [FormidableLabs/spectacle-editor#166]
Lots of Â characters are sneaking into this presentation when it is uploaded to the viewer.

View in SpecEd:

![image](https://cloud.githubusercontent.com/assets/1865834/18056950/0a179b7a-6ddc-11e6-8950-00367cb15977.png)

View in viewer:

![image](https://cloud.githubusercontent.com/assets/1865834/18056905/e30ccd5c-6ddb-11e6-8faf-b0fbaade07f5.png)

https://plot.ly/~jackp/16661#/2?_k=mtrdxr

**Comment by bmathews** [comment]
@jackparmer Was this uploaded from https://plot.ly/organize/ or from the editor?

**Comment by bmathews** [comment]
@jackparmer I've verified that uploading from `/organize` creates these encoding issues, but uploading from the editor does not.

**Comment by jackparmer** [comment]
Uploaded from /organize, but it looks like the same API endpoint.

**Comment by rgerstenberger** [comment]
@jackparmer @bmathews it sounds like the `/organize` endpoint is messing with encoding. @mdtusz may be able to investigate, but I don't think there's anything we can change on our end to solve this.

**Comment by mdtusz** [comment]
Good catch - we're using `FileReader.readAsBinaryString` but switching it to `readAsText` or doing something to fix the encoding when sent over the wire should remedy it.
