### ISSUE TITLE
Element drag/drop snap to grid

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#17]
When dragging an element to the canvas, snap to a predefined (and visible) grid like other presentation tools. This includes snapping to center alignment of the canvas. Allow for the grid + snapping to be a toggleable option in view menu.

Does not need to snap to other element alignment.

Depends on #16

**Comment by coopy** [comment]
This is complete - closing

**Comment by coopy** [comment]
Complete except for View menu options. Extracted to https://github.com/FormidableLabs/spectacle-editor/issues/80. Closing.
