### ISSUE TITLE
Full width/height background images

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#178]
Support background images at the slide level. UI would be same file picker as image menu but live at the slide menu level under background color. Opacity slider would be a nice to have so background color and image could be set at the same time.

**Comment by coopy** [comment]
Is this the same issue as "full-bleed" images?
E.g. http://help.plot.ly/sample-presentations/gates/#/?_k=zept0t

**Comment by rgerstenberger** [comment]
Yes, though I'm not sure if it requires changes to scaling logic to make the background truly "full-bleed".
