### ISSUE TITLE
Element drag/drop snap to other elements

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#18]
Make dragging elements snap to top/bottom/left/right/center of existing elements on the canvas. Similar to other design/presentation tools.

Depends on #17

**Comment by coopy** [comment]
Snapping to center is complete.

**Comment by coopy** [comment]
Snapping to left is complete.

**Comment by coopy** [comment]
Snapping to bottom and right of image element is complete.
