### ISSUE TITLE
Image save and upload

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/spectacle-editor#55]
Allow users to select an image from the filesystem and have it work with slide background and the image element. Figure out image upload when saving presentation to Plotly server.

**Comment by rgerstenberger** [comment]
This should serialize the image into the JSON representation of the slides. Ideally we add compression during serialization.

Also includes image size cap.

Must handle JPG, PNG, GIF

**Comment by coopy** [comment]
@rgerstenberger Can this be closed? Image size cap is duplicated by https://github.com/FormidableLabs/spectacle-editor/issues/107.

**Comment by rgerstenberger** [comment]
Yes, can close.
