### ISSUE TITLE
Code element

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/spectacle-editor#82]
Support Spectacle `<Code/>` element with monospace font rendering

**Comment by jackparmer** [comment]
Would be great to have support for the R programming language:
http://mathematicalcoffee.blogspot.com/2013/05/a-prism-syntax-highlighter-for-r.html

**Comment by coopy** [comment]
Wishlist: Syntax highlighting support for these languages:

- JavaScript
- Python
- R
- MATLAB

Using [`react-codemirror`](https://github.com/JedWatson/react-codemirror), we will get syntax highlighting for free.

Theming is straightforward: https://codemirror.net/demo/theme.html#blackboard

Language detection is more involved: http://stackoverflow.com/a/9675540
