### ISSUE TITLE
Support keyboard events

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/spectacle-editor#93]
Text element
- ESC from text element finalizes it
- Enter in text element makes a newline

Undo/Redo
- Super+z Undo
- Super+Shift+z Redo

**Comment by coopy** [comment]
Take care that undo-redo inside a text element does not result in undo/redo of the slide state (the app undo/redo should be disabled while editing text/lists/etc)

**Comment by rgerstenberger** [comment]
Delete element
